name: "Push"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        type: boolean
        default: false
      version:
        description: "Version Tag"
        type: string
  #push:
  #  branches: ["**"]

env:
  version: ${{ github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  matrix:
    name: "Matrix - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        continue-on-error: true
        shell: bash
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        shell: bash
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        shell: bash
        run: env

      - name: "Debug"
        continue-on-error: true
        shell: bash
        run: |
          echo github.repository: ${{ github.repository }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name: ${{ github.ref_name  }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.version: ${{ inputs.version }}
          echo env.version: ${{ env.version }}

      # BEGIN CUSTOM

      - name: "Test 1"
        continue-on-error: true
        shell: bash
        run: |
          echo test

      # END CUSTOM

      ## Optioanl Fail Job for Debugging
      - name: "Fail"
        if: ${{ inputs.fail }}
        shell: bash
        run: |
          exit 1
